### ISSUE TITLE
Corner dots are clipped

### ISSUE THREAD

**Issue by DmitrySikorsky** [chooyan-eng/crop_your_image#111]
Hi,

Please add `clipBehavior: Clip.none,` to the stacks, so the corner dots won't be clipped if padding is added around the cropper.

![sample](https://github.com/chooyan-eng/crop_your_image/assets/6570196/6844f75b-b39a-45ed-ae9c-86794e6db5bd)

Thank you.

**Comment by chooyan-eng** [comment]
@DmitrySikorsky 
Thank you for your feedback.
I believe this PR would solve this issue. 

https://github.com/chooyan-eng/crop_your_image/pull/125
