### ISSUE TITLE
Zoom on Desktop not working

### ISSUE THREAD

**Issue by tolotrasamuel** [chooyan-eng/crop_your_image#120]
I tried with macos, the zoom is not working,

Maybe because you use ` if (_pointerNum >= 2) ` in desktop, we use track pad to zoom, there is no pointer down event

**Comment by chooyan-eng** [comment]
@tolotrasamuel 
Thanks, I just checked your PR #121 
Does this change work fine for other platforms, such like Android, iOS or Web?
