### ISSUE TITLE
Is it possible to put a limit to the zoom?

### ISSUE THREAD

**Issue by KingOfPeru** [chooyan-eng/crop_your_image#123]

**Comment by chooyan-eng** [comment]
@KingOfPeru 
Added `allowScale` function to `Crop` constructor.

Try the snippet below. 

```dart
const maxScale = 3.0;
Crop(
  allowScale: (newScale) => newScale < maxScale,
),
```

**Comment by chooyan-eng** [comment]
@KingOfPeru 
Sorry for confusion, but `allowScale` is renamed to `willUpdateScale` from `1.0.0-dev.2` for a versatility reason.

https://github.com/chooyan-eng/crop_your_image/pull/127
