### ISSUE TITLE
sometimes will throw InvalidRectError

### ISSUE THREAD

**Issue by namezcc** [chooyan-eng/crop_your_image#142]
When I move the image to the edge,The _cropFunc function in the crop.dart file may sometimes have rect.right or rect.bottom values that are 0.00...0X larger than originalImage.width or originalImage.height.
i think can change code with: bottomRight: Offset(min(rect.right, originalImage.width), min(rect.bottom, originalImage.height)) ?

**Comment by chooyan-eng** [comment]
@namezcc Thank you for your feedback and suggestion! I'll try to reproduce it first.

**Comment by orkun1675** [comment]
I'm experiencing the same error sometimes on web.

**Comment by chooyan-eng** [comment]
I've fixed this issue with `1.0.2`. Thank you for your feedback!
