### ISSUE TITLE
Instance of 'InvalidRectError'

### ISSUE THREAD

**Issue by ygx-123456** [chooyan-eng/crop_your_image#150]
When I triggered the cropController.crop() method, an error occurred:
Instance of 'InvalidRectError'
image_image_cropper.dart in ImageImageCropper.call at line 35 within crop_your_image
crop.dart in _cropFunc at line 765 within crop_your_image
_isolates_io.dart in compute.<fn> at line 19 within flutter
isolate in _RemoteRunner._run at line 1090
isolate in _RemoteRunner._remoteExecute at line 1084
isolate_patch.dart in _delayEntrypointInvocation.<fn> at line 300
isolate_patch.dart in _RawReceivePort._handleMessage at line 184

package version crop_your_image: ^1.0.2
iphone 12 Pro  
IOS17.1.2 
flutter 3.19.5
dart 3.2.3
image data: 
![b74ed962e6aa74e51c2f3dc619fcfbf8](https://github.com/chooyan-eng/crop_your_image/assets/73324161/cea86add-8a17-430f-ab98-d43a387fef40)

**Comment by yeikel16** [comment]
Hi @ygx-123456, I have the same error in console, you can use the `initialRectBuilder` method in the `Crop` widget. This worked for me.

```dart
initialRectBuilder: (viewportRect, imageRect) => imageRect,
```

**Comment by disilva21** [comment]
Tenho o mesmo problema, fiz o que @yeikel16  recomendou mas não funcionou. Pelo que vi, sempre que da o zoom na imagem para fazer o crop até os limites da imagem da esse problema.

Exemplo que dá o erro: 
![image](https://github.com/chooyan-eng/crop_your_image/assets/51758628/20d43059-3e5d-4175-9b07-c6e790653ef6)

Exemplo que funciona:
![image](https://github.com/chooyan-eng/crop_your_image/assets/51758628/8739e42c-c2e1-4dee-b986-c13ae2818308)


Se alguém puder ajudar, agradeço!

**Comment by chooyan-eng** [comment]
@ygx-123456 Thank you for reporting. I believe version `2.0.0-dev.6` or above will resolve this issue.
