### ISSUE TITLE
InvalidRectError

### ISSUE THREAD

**Issue by kaurin-liebrecht-haas** [chooyan-eng/crop_your_image#152]
![image](https://github.com/chooyan-eng/crop_your_image/assets/162134613/35221d09-50f7-4d05-9a53-0265d0a1a316)

topLeft.dy.isNegative = -5.211189645992988e-13

Floating Point Precision Error? 

running on:
Flutter 3.19.2 
Tools • Dart 3.3.0 • DevTools 2.31.1

**Comment by Schefferbird** [comment]
I hade the same issue with 1.1.0. I have downgraded to 1.0.0 to get rid of this issue.

**Comment by chooyan-eng** [comment]
@kaurin-liebrecht-haas @Schefferbird Thank you for reporting! I believe version `2.0.0-dev.6` or above will resolve this issue.
