### ISSUE TITLE
not working with image: ^4.2.0

### ISSUE THREAD

**Issue by kaun9144** [chooyan-eng/crop_your_image#155]
Throws error : ImageFormat imported from both

**Comment by bluedeep** [comment]
/Users/local/.pub-cache/hosted/pub.dev/crop_your_image-1.0.2/lib/src/logic/cropper/image_image_cropper.dart:13:1: Error: 'ImageFormat' is imported from both 'package:crop_your_image/src/logic/format_detector/format.dart' and 'package:image/src/formats/image_format.dart'.

**Comment by sandrush73** [comment]
go to format.dart and comment it out will work

**Comment by kaun9144** [comment]
I used temporary workaround by overriding it like this.
dependency_overrides:
  image: 4.1.7

**Comment by Dineshkumar-Sridharan** [comment]
dependency_overrides couldn't resolve the problem. Its getting overridden again from crop_your_image transitive dependency 

![image](https://github.com/chooyan-eng/crop_your_image/assets/73074777/06b9c089-677f-4080-8ada-e95a1999b35d)
