### ISSUE TITLE
Please check your package has analysis issues and please update as soon as possible

### ISSUE THREAD

**Issue by vikrant-p-nimap** [chooyan-eng/crop_your_image#156]
Performing hot restart...
Waiting for connection from debug service on Chrome...
../../.pub-cache/hosted/pub.dev/crop_your_image-1.0.2/lib/src/logic/cropper/image_image_cropper.dart:13:1: Error: 'ImageFormat' is imported from both 'package:crop_your_image/src/logic/format_detector/format.dart' and 'package:image/src/formats/image_format.dart'.
import 'package:image/image.dart';
^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/crop_your_image-1.0.2/lib/src/logic/cropper/image_image_cropper.dart:24:32: Error: Not a constant expression.
    ImageFormat outputFormat = ImageFormat.jpeg,
                               ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/crop_your_image-1.0.2/lib/src/logic/cropper/image_image_cropper.dart:24:32: Error: 'ImageFormat' is imported from both 'package:crop_your_image/src/logic/format_detector/format.dart' and 'package:image/src/formats/image_format.dart'.
    ImageFormat outputFormat = ImageFormat.jpeg,
                               ^^^^^^^^^^^

**Comment by chooyan-eng** [comment]
@vikrant-p-nimap Thank you for reporting this issue. I've fixed this by merging #154 and published 1.1.0.
