### ISSUE TITLE
Crop images with circle shape

### ISSUE THREAD

**Issue by chooyan-eng** [chooyan-eng/crop_your_image#2]

**Comment by kiaxseventh** [comment]
does it support  Crop images with circle shape ?

**Comment by chooyan-eng** [comment]
@kiaxseventh 

I’m thinking to support but not yet.
I’m going to tackle it in this week.

**Comment by kiaxseventh** [comment]
it's amazing feature
I wish you success

**Comment by chooyan-eng** [comment]
@kiaxseventh 
Hi. I just updated this package, and now circle shape is available at version of 0.2.1.

Pass `isCircle: false` to Crop instance or `CropController`.

![cropyourimage](https://user-images.githubusercontent.com/20849526/111283696-bd9d3880-8682-11eb-9db6-37ba21b38412.gif)

Though It's still minimum implementation and UI is not very nice, I'll be happy if you try this package and give me some feedback.

**Comment by kiaxseventh** [comment]
thank you lot of 
can you add just Circle crop UI
on end output image Square 1:1

i need just on crop see Circle UI like your feature but end image a Square image but size like on circle ui

**Comment by chooyan-eng** [comment]
@kiaxseventh 
OK. I now understand what you need.

I have a plan below

- `isCircle` flag only affects to UI.
- add `CropController.cropCircle` method for those who need cropped images with circle shape.

In other words, you can obtain square shape image as long as cropping with `CropController.crop` method regardless of `isCircle`  flag.

**Comment by chooyan-eng** [comment]
The idea above is available at `0.2.2`. You can output with both square and circle regardless of the cropping UI.

![cyi](https://user-images.githubusercontent.com/20849526/111295966-4fab3e00-868f-11eb-9e59-6c2ae1a0ab72.gif)

**Comment by kiaxseventh** [comment]
thank you  
I look forward to version 0.2.2

**Comment by chooyan-eng** [comment]
0.2.2 is already published and available via pub.dev.
Thanks.

**Comment by kiaxseventh** [comment]
I checked it
but it have error for get pub dev !

```
Error on line 28, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
28 │   crop_your_image: ^0.2.1
   │   ^^^^^^^^^^^^^^^
   ╵
pub get failed (65;    ╵)
```

**Comment by chooyan-eng** [comment]
@kiaxseventh 

I’m not sure what is happening, but can you check if your project name is also "crop_your_image"?

I guess the issue below would be the similar situation.
https://github.com/felangel/bloc/issues/181

**Comment by kiaxseventh** [comment]
thank you very much
You helped me a lot
