### ISSUE TITLE
big image problem

### ISSUE THREAD

**Issue by kiaxseventh** [chooyan-eng/crop_your_image#31]
dear @chooyan-eng 
thank you for this good crop image i like it

it has one problem on big image

you can see it on this video :

https://user-images.githubusercontent.com/15640035/112752765-d0e8c600-8fe9-11eb-9a58-a6d4ad571431.mp4

**Comment by kiaxseventh** [comment]
dear @chooyan-eng are you have idea for fix it ?

**Comment by chooyan-eng** [comment]
@kiaxseventh 
Oops, I haven't noticed this issue has come 2 days ago.

Now, I'll check it. 
Can you provide me your code of this page and the size of the image?

Thank you for using anyways!

**Comment by kiaxseventh** [comment]
_these are my image sizes :_
```
1816 x 4032
2268 x 4032
3024 x 4032
3024 x 3024   it's ok don't have problem
```



_pubspec.yaml_
```yaml
  crop_your_image: ^0.5.2+1
  image_picker: ^0.7.3
```

_main.dart_
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FirstScreenFilePicker(),
    );
  }
}

class FirstScreenFilePicker extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Crop Your Image Demo'),
      ),
      body: Center(
        child: Container(
          margin: EdgeInsets.all(32),
          child: FlatButton(
            child: Text(
              'Pick Image',
              style: TextStyle(color: Colors.white),
            ),
            color: Colors.blue,
            onPressed: () async {
              PickedFile pickedFile = await ImagePicker().getImage(source: ImageSource.gallery);
              Uint8List bytes = await pickedFile.readAsBytes();
              Navigator.push(context, MaterialPageRoute(builder: (context) => CropImageScreen2(imageData: bytes)));
            },
          ),
        ),
      ),
    );
  }
}

```


_crop_image_screen.dart_


```dart
class CropImageScreen extends StatelessWidget {
  CropImageScreen({this.imageData});

  final Uint8List imageData;
  final controller = CropController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Crop(
        image: imageData,
        controller: controller,
        onCropped: (image) {
          // do something with image data
        },
        aspectRatio: 1 / 1,
        initialSize: 0.5,
        withCircleUi: true,
        baseColor: Colors.black,
        maskColor: Colors.black.withAlpha(100),
        onMoved: (newRect) {
          // do something with current cropping area.
        },
        cornerDotBuilder: (size, cornerIndex) => const DotControl(color: Colors.blue),
      ),
    );
  }
}

```

**Comment by chooyan-eng** [comment]
@kiaxseventh 
Thank you for additional information! I'll try to reproduce the same issue to fix.

**Comment by ianholing** [comment]
Same issue here

**Comment by chooyan-eng** [comment]
@kiaxseventh @ianholing 
I generated some image files with exact the same size but I could not reproduce the issue on my iPhone or Android either.

If possible, can you upload the image files you selected?

**Comment by chooyan-eng** [comment]
OK, I've found other image file in my photos which reproduce the issue.
I'll check the difference to find what causes this issue. I hope you'll wait for my fixing and update. Thanks.

**Comment by chooyan-eng** [comment]
@kiaxseventh @ianholing 
I fixed this bug at #32 , and released version `0.5.3` including this bugfix.

Change Log:
https://pub.dev/packages/crop_your_image/changelog

I'll be happy if you try `0.5.3` and leave the result here if your issues are solved or not.

**Comment by kiaxseventh** [comment]
thank you 
this issue has been fixed

**Comment by ianholing** [comment]
Sure, works like charm, thank you!
