### ISSUE TITLE
Is there any way to get the cropped image as a file

### ISSUE THREAD

**Issue by ndrsrc** [chooyan-eng/crop_your_image#36]
Is there any way to get a file from oncropped property? How can I convert uint8list to a File.

**Comment by chooyan-eng** [comment]
Hi.
Though I guess you could solve the issue, I just write my suggestion for others who find this issue with the same question.

As the type `Uint8List` is available as pure dart code, which is in `dart:typed_data`, you can just write ordinal way to save data as a file (maybe using `writeAsBytes()` method in File API in `dart:io`.

Thanks.
