### ISSUE TITLE
Version solving failed due to flutter_driver

### ISSUE THREAD

**Issue by jayant0jhaSanskrut** [chooyan-eng/crop_your_image#37]
I am getting error in running `flutter pub get` because version solving fails.

`Because every version of flutter_driver from sdk depends on webdriver 2.1.2 which depends on archive >=1.0.0 <3.0.0, every version of flutter_driver from sdk requires archive >=1.0.0 <3.0.0.
And because every version of crop_your_image depends on image ^3.0.1 which depends on archive ^3.0.0, flutter_driver from sdk is incompatible with crop_your_image.
So, because project depends on both crop_your_image ^0.5.3 and flutter_driver any from sdk, version solving failed.
Running "flutter pub get" in project...                             
pub get failed (1; So, because project depends on both crop_your_image ^0.5.3 and flutter_driver any from sdk, version solving failed.)`

As the version is clashing with flutter sdk I cannot understand how to fix. Let me know if I need to add any more required information to help me fix it.

**Comment by 2math** [comment]
https://github.com/chooyan-eng/crop_your_image/issues/29#issuecomment-832148513
