### ISSUE TITLE
[Feature] Pan & Zoom the Image Itself into a Fixed Frame Instead of Positioning the Cropping Box

### ISSUE THREAD

**Issue by yasinarik** [chooyan-eng/crop_your_image#38]
The general way of cropping with this package is to change the rectangular box's dimensions and position. It's very good indeed. 

I would like you to provide an opposite way of that. Let us change the position and scale of the underlying image by panning & zooming while keeping the cropper box at the center with a selected aspect ratio. 

So instead of us moving the cropping rectangle, we would be dragging the image itself until it is positioned in a stationary cropping frame.

It will be like the cropper of the Instagram's post sharing screen. This is very intuitive for users to adapt.

There is another package on pub.dev for cropping as I said; however, I think your package is better at the moment and if you can implement what I say in this issue, it will be superior. 

Thanks a lot!

**Comment by chooyan-eng** [comment]
@yasinarik 
Thank you for your nice feedback!
I like your idea of panning & zooming images with fixed box. I'll challenge this feature for the next update.

**Comment by chooyan-eng** [comment]
@yasinarik 
Finally the feature is experimentally added to `Crop` widget.

Try `interactive` parameter to enable panning and zooming, and `fixArea` parameter to fix the rectangular box like below.

```
Crop(
  .. existing parameters ..
  interactive: true,
  fixArea: true,
),
```

Thanks.
