### ISSUE TITLE
How to change UI while the image is being cropped

### ISSUE THREAD

**Issue by logic-and-math** [chooyan-eng/crop_your_image#39]
Since crop function is not async I am not sure how to show a loading indicator while the image is being cropped, any suggestions ?

**Comment by logic-and-math** [comment]
I figured it out, I need to set a flag before cropping is started, then rebuild the with the new flag and then start the cropping. With setState this is intuitive, but with other state managements methods it's a bit weird. Any chance that this can be converted to a future that can be awaited for?

**Comment by chooyan-eng** [comment]
@logic-and-math 
Thank you for your suggestion. 
Related Pull Request #42 is now open so I'm glad if you also check the PR and post your feedback.

**Comment by chooyan-eng** [comment]
@logic-and-math as `progressIndicator` is now available, let me close the issue.
