### ISSUE TITLE
Freeze UI

### ISSUE THREAD

**Issue by DrobyshevAlex** [chooyan-eng/crop_your_image#44]
The code in this line takes a very long time to execute
https://github.com/chooyan-eng/crop_your_image/blob/7bf38421e5469b212e9d7a2dc574d29f8f6a4f4f/lib/src/crop.dart#L192

I think it must be async or move to Isolate.

**Comment by chooyan-eng** [comment]
@DrobyshevAlex 
Thank you for your suggestion!
I'll try this to enhance this package.

**Comment by chooyan-eng** [comment]
I've done this issue on #46 and published as updated version `0.6.0`.
