### ISSUE TITLE
Widget fails in WidgetTest

### ISSUE THREAD

**Issue by NikoBoerger** [chooyan-eng/crop_your_image#55]
Hi, 

I'm having a hard time writing widget tests, when I use your widget. Have you ever tried using your widget in a widget test?
It seems like images are not getting loaded, no matter how long I wait in the widget test.

Do you have any suggestions on that?

Thanks!

**Comment by chooyan-eng** [comment]
@NikoBoerger 
Thank you for your feedback.
Unfortunately I've never tried widget tests of `Crop`, though I should do.

Can you provide some code of your widget test?

**Comment by chooyan-eng** [comment]
@NikoBoerger 

https://github.com/chooyan-eng/crop_your_image/pull/75 solve this problem and it's released with the version `0.7.3`. 
Thank you for reporting.
