### ISSUE TITLE
[PROPOSAL] Give ability to customize the loading indicator

### ISSUE THREAD

**Issue by PTLam25** [chooyan-eng/crop_your_image#56]
Hi! It will be very good to have access to change the progress indicator.

Could you please add a new parameter to the Crop widget, so we can pass our custom progress indicator widget? Many thank in advance.

![image](https://user-images.githubusercontent.com/83693224/144073848-92dea7ae-6e5a-44b8-af62-93243ed831e2.png)

**Comment by vixez** [comment]
I have this feature already in PR: https://github.com/chooyan-eng/crop_your_image/pull/49

**Comment by chooyan-eng** [comment]
@PTLam25 
Thank you for the feedback.

@vixez 
Thank you for your PR! I'll check this.

**Comment by chooyan-eng** [comment]
I just added `progressIndicator` parameter to `Crop` class. You can check the change in https://github.com/chooyan-eng/crop_your_image/pull/75 .

@vixez 
I checked your PR and I could make the PR above using your idea. I didn't merge your PR as is but I separated "loading widget" part into https://github.com/chooyan-eng/crop_your_image/pull/75 and fixed param name and how default widget is set. Thanks!
