### ISSUE TITLE
The cropping image is too large when interactive is true

### ISSUE THREAD

**Issue by KT99-bit** [chooyan-eng/crop_your_image#70]
After the value of 'interactive' was set to true, the cropping image shown on the screen turned too large.
When interactive was false, the cropping image automatically fitted the width of the screen or another.
I tried to reset the size of the cropping image shown on the screen.
So I looked up for the parameter to resize the initial size of the cropping image, but there wasn't.
What I wanted to was to resize the shown image to crop hoping you to add a new parameter function such as initialImageSize for instance.

{ImageSize Function()? imageSize} 
Type: ImageSize Function()?

ImageSize({double? width, double? height});

Example
initialImageSize: ImageSize(width, height);

With the param, initialImageSize, the image to crop will be shown possibly to fit either of the width or the height of the screen with 'interactive' set to true.

**Comment by 0xManjeet** [comment]
facing the same issue on v0.7.5
