### ISSUE TITLE
Custom crop overlay frame

### ISSUE THREAD

**Issue by JayronKhong** [chooyan-eng/crop_your_image#86]
Hi, is this package able to make a custom overlay cropper frame?
I'm trying to crop the image base on the custom overlay.

Example screenshot:
![Screenshot 2023-01-11 at 11 28 29 AM](https://user-images.githubusercontent.com/50298326/211711247-acea2817-24a1-41c4-80b6-5c426aaa475c.png)

**Comment by chooyan-eng** [comment]
@JayronKhong 
Thank you for asking and I apologize for the late reply.
Though it depends on what UI you need to build, you can simply place your overlay using `Stack` like below.

```dart
Stack(
  children: [
    SizedBox(  // or some Widget to provide the size to its child
      child: Crop(),
    ),
    Positioned.fill(
      child: IgnorePointer(
        child: YourOverlayWidget();
      ),
    ),
  ],
),
```
